"""Shell completion script generation for the ``completions`` subcommand.

``prompter completions zsh`` (or ``bash``) prints a completion script to stdout,
ready to redirect to a file. The script is what the shell loads to offer tab
completion; this module only renders it.

This module knows shells, not commands. The command surface it completes is
passed in as a ``CommandSurface``, which the CLI builds from the very parser and
dispatch table it runs on (``cli.command_surface``). So a generated script
cannot list a command, flag, or provider the CLI does not actually have, and
there is nothing here to keep in sync by hand.
"""

from __future__ import annotations

from dataclasses import dataclass

from .config import PROGRAM_NAME
from .constants import PIPE, SPACE

ZSH = "zsh"
BASH = "bash"
SUPPORTED_SHELLS = (ZSH, BASH)


@dataclass(frozen=True)
class CommandSurface:
    """Everything a completion script needs, derived from the live CLI.

    ``value_flags`` are flags that take an argument; the two that take a *known*
    kind of argument call it out (``provider_flags`` complete to a provider name,
    ``dir_flags`` to a directory). Any value flag in neither group takes a
    free-form argument, so completion offers nothing after it -- a fact derived
    here, not annotated.
    """

    commands: tuple[str, ...]
    bool_flags: tuple[str, ...]
    value_flags: tuple[str, ...]
    provider_flags: tuple[str, ...]
    dir_flags: tuple[str, ...]
    keys_actions: tuple[str, ...]
    keys_provider_actions: tuple[str, ...]
    providers: tuple[str, ...]

    @property
    def run_flags(self) -> tuple[str, ...]:
        return self.value_flags + self.bool_flags

    @property
    def freeform_flags(self) -> tuple[str, ...]:
        special = set(self.provider_flags) | set(self.dir_flags)
        return tuple(f for f in self.value_flags if f not in special)


_ZSH_TEMPLATE = """\
#compdef {program}
# zsh completion for {program}. Generated by `{program} completions zsh`.
#
# Install (one time):
#   mkdir -p ~/.zsh/completions
#   {program} completions zsh > ~/.zsh/completions/_{program}
#   # then, in ~/.zshrc before `compinit`:
#   #   fpath=(~/.zsh/completions $fpath)
#   #   autoload -Uz compinit && compinit
# Open a new shell and press TAB after `{program}`.

_{program}() {{
  local -a commands providers keys_actions run_flags
  commands=({commands})
  providers=({providers})
  keys_actions=({keys_actions})
  run_flags=({run_flags})

  case ${{words[CURRENT-1]}} in
{value_flag_cases}
  esac

  if (( CURRENT == 2 )); then
    _describe 'command' commands
    _describe 'flag' run_flags
    return
  fi

  case ${{words[2]}} in
    keys)
      if (( CURRENT == 3 )); then
        _describe 'keys action' keys_actions
      elif (( CURRENT == 4 )) && [[ ${{words[3]}} == ({keys_provider_actions}) ]]; then
        _describe 'provider' providers
      fi
      ;;
    use)
      (( CURRENT == 3 )) && _describe 'provider' providers
      ;;
    *)
      _describe 'flag' run_flags
      ;;
  esac
}}

_{program} "$@"
"""

_BASH_TEMPLATE = """\
# bash completion for {program}. Generated by `{program} completions bash`.
#
# Install (one time), either:
#   {program} completions bash > "$(brew --prefix)/etc/bash_completion.d/{program}"
# or append to ~/.bashrc:
#   source <({program} completions bash)
# Open a new shell and press TAB after `{program}`.

_{program}() {{
  local cur prev
  cur=${{COMP_WORDS[COMP_CWORD]}}
  prev=${{COMP_WORDS[COMP_CWORD-1]}}

  local commands="{commands}"
  local providers="{providers}"
  local keys_actions="{keys_actions}"
  local run_flags="{run_flags}"

  case $prev in
{value_flag_cases}
  esac

  if (( COMP_CWORD == 1 )); then
    COMPREPLY=( $(compgen -W "$commands $run_flags" -- "$cur") ); return
  fi

  case ${{COMP_WORDS[1]}} in
    keys)
      if (( COMP_CWORD == 2 )); then
        COMPREPLY=( $(compgen -W "$keys_actions" -- "$cur") )
      elif (( COMP_CWORD == 3 )) && [[ ${{COMP_WORDS[2]}} =~ ^({keys_provider_actions})$ ]]; then
        COMPREPLY=( $(compgen -W "$providers" -- "$cur") )
      fi
      ;;
    use)
      (( COMP_CWORD == 2 )) && COMPREPLY=( $(compgen -W "$providers" -- "$cur") )
      ;;
    *)
      COMPREPLY=( $(compgen -W "$run_flags" -- "$cur") )
      ;;
  esac
}}

complete -F _{program} {program}
"""

# Per-shell branch bodies for completing a flag's argument. {pattern} is filled
# with the flags that share that body (e.g. "--provider").
_BRANCHES = {
    ZSH: {
        "provider": "{pattern}) _describe 'provider' providers; return ;;",
        "dir": "{pattern}) _path_files -/; return ;;",
        "freeform": "{pattern}) return ;;",
    },
    BASH: {
        "provider": '{pattern}) COMPREPLY=( $(compgen -W "$providers" -- "$cur") ); return ;;',
        "dir": "{pattern}) COMPREPLY=( $(compgen -d -- \"$cur\") ); return ;;",
        "freeform": "{pattern}) return ;;",
    },
}
_CASE_INDENT = "    "


def _value_flag_cases(shell: str, surface: CommandSurface) -> str:
    """Render the case arms that complete the argument of a value-taking flag."""
    branches = _BRANCHES[shell]
    groups = (
        ("provider", surface.provider_flags),
        ("dir", surface.dir_flags),
        ("freeform", surface.freeform_flags),
    )
    arms = [
        _CASE_INDENT + branches[kind].format(pattern=PIPE.join(flags))
        for kind, flags in groups if flags
    ]
    return "\n".join(arms)


def render(shell: str, surface: CommandSurface) -> str:
    """Return the completion script for ``shell`` (one of SUPPORTED_SHELLS)."""
    template = _ZSH_TEMPLATE if shell == ZSH else _BASH_TEMPLATE
    return template.format(
        program=PROGRAM_NAME,
        commands=SPACE.join(surface.commands),
        providers=SPACE.join(surface.providers),
        keys_actions=SPACE.join(surface.keys_actions),
        run_flags=SPACE.join(surface.run_flags),
        keys_provider_actions=PIPE.join(surface.keys_provider_actions),
        value_flag_cases=_value_flag_cases(shell, surface),
    )
